/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

export interface TranslationSet {
  splashText: string;
  loginTitle: string;
  loginSubtitle: string;
  registerTitle: string;
  registerSubtitle: string;
  nexusIdLabel: string;
  passwordLabel: string;
  nameLabel: string;
  bioLabel: string;
  avatarLabel: string;
  loginBtn: string;
  registerBtn: string;
  backupWarning: string;
  backupWarningTitle: string;
  notRegisteredYet: string;
  alreadyRegistered: string;
  recoverBtn: string;
  chatsTab: string;
  callsTab: string;
  statusTab: string;
  contactsTab: string;
  settingsTab: string;
  searchPlaceholder: string;
  noChats: string;
  onlineText: string;
  typingText: string;
  offlineText: string;
  lastSeenText: string;
  callIncoming: string;
  callOutgoing: string;
  callConnected: string;
  callConnecting: string;
  callEnded: string;
  muteMicrophone: string;
  speakerMode: string;
  hangupBtn: string;
  acceptBtn: string;
  rejectBtn: string;
  statusPrivacyLabel: string;
  readReceiptsLabel: string;
  blockedUsersLabel: string;
  themeLabel: string;
  accentColorLabel: string;
  bubbleColorLabel: string;
  languageLabel: string;
  securityLabel: string;
  archiveCheck: string;
  lockCheck: string;
  pollQuestion: string;
  pollOptions: string;
  pollCreateBtn: string;
  desktopModeLabel: string;
  activeNow: string;
  copiedToken: string;
  backupSuccess: string;
  restoreSuccess: string;
  aboutSection: string;
  starredLabel: string;
  saveIdTitle: string;
  saveIdDesc: string;
  savedBtn: string;
  muteCheck: string;
  clearCheck: string;
  typingIndicatorLabel: string;
  uploadQualityLabel: string;
}

export const translations: Record<string, TranslationSet> = {
  en: {
    splashText: "Secure. Distributed. Virtual ID Messaging.",
    loginTitle: "Login to Nexus Messenger",
    loginSubtitle: "Access your global communications panel instantly",
    registerTitle: "Get registered",
    registerSubtitle: "Claim your custom virtual Nexus ID automatically",
    nexusIdLabel: "Nexus ID (started with +0)",
    passwordLabel: "Account Password",
    nameLabel: "Your Display Name",
    bioLabel: "Status bio/About info",
    avatarLabel: "Profile Picture Profile URL/Base64",
    loginBtn: "Authenticate Session",
    registerBtn: "Generate Nexus ID & Enter",
    backupWarning: "Save your Nexus ID carefully. Combined with your password, it allows full cloud recovery of profile, chats, statuses, and history on any device.",
    backupWarningTitle: "Nexus Virtual Identity Warning",
    notRegisteredYet: "New here? Register to claim your virtual ID",
    alreadyRegistered: "Already registered? Authentication panel",
    recoverBtn: "Manage Cloud Restoration",
    chatsTab: "Chats",
    callsTab: "Calls",
    statusTab: "Status",
    contactsTab: "Contacts",
    settingsTab: "Settings",
    searchPlaceholder: "Search chats, contacts, or Nexus IDs...",
    noChats: "No conversations discovered. Type in Contacts or add IDs to begin chatting!",
    onlineText: "Active Now",
    typingText: "typing...",
    offlineText: "Offline",
    lastSeenText: "Last seen recently",
    callIncoming: "Incoming digital voice call...",
    callOutgoing: "Outgoing satellite link...",
    callConnected: "Encrypted connection established",
    callConnecting: "Initializing secure link...",
    callEnded: "Call ended gracefully",
    muteMicrophone: "Mute",
    speakerMode: "Speaker",
    hangupBtn: "Disconnect",
    acceptBtn: "Receive Call",
    rejectBtn: "Decline",
    statusPrivacyLabel: "Status Publication Privacy",
    readReceiptsLabel: "Read receipts (Seen double ticks)",
    blockedUsersLabel: "Blocked Connections",
    themeLabel: "Visual interface look",
    accentColorLabel: "Focal Accent Element Style",
    bubbleColorLabel: "My message bubble color",
    languageLabel: "Internal Platform Language",
    securityLabel: "Quantum Cryptography Sync",
    archiveCheck: "Archive Chat",
    lockCheck: "Lock chat (requires validation PIN)",
    pollQuestion: "Poll Enquiry Topic",
    pollOptions: "Choices (Comma separated)",
    pollCreateBtn: "Deploy Interactive Poll",
    desktopModeLabel: "Forced Desktop Window Alignment",
    activeNow: "Active global sessions",
    copiedToken: "Nexus Digital ID copied to clipboard!",
    backupSuccess: "Encrypted cloud database recovery synchronized successfully!",
    restoreSuccess: "Cloud profile, media logs, contacts and archived chats recovered!",
    aboutSection: "Nexus Messenger runs end-to-end encrypted chats over virtual identification metrics (+0) bypassing any cellular standard requirement.",
    starredLabel: "Starred Highlights",
    saveIdTitle: "Nexus Identity Granted!",
    saveIdDesc: "Here is your permanently assigned Nexus Virtual Identity. Copy and save it securely with your password to access your cloud logs anytime.",
    savedBtn: "I have stored it safely",
    muteCheck: "Mute Notification Feeds",
    clearCheck: "Wipe Chat History Logs",
    typingIndicatorLabel: "Typing Status Broadcast",
    uploadQualityLabel: "Media Upload Bandwidth Profiles"
  },
  ur: {
    splashText: "محفوظ۔ تقسیم شدہ۔ ورچوئل آئی ڈی میسجنگ۔",
    loginTitle: "نیکسس میسنجر لاگ ان",
    loginSubtitle: "اپنے عالمی مواصلاتی پینل تک فوری رسائی حاصل کریں",
    registerTitle: "نیا اکاؤنٹ بنائیں",
    registerSubtitle: "اپنا ورچوئل نیکسس آئی ڈی خودکار طور پر حاصل کریں",
    nexusIdLabel: "نیکسس آئی ڈی (+0 سے شروع)",
    passwordLabel: "سیکیورٹی پاس ورڈ",
    nameLabel: "آپ کا ڈسپلے نام",
    bioLabel: "مختصر بائیو (بابت معلومات)",
    avatarLabel: "پروفائل تصویر",
    loginBtn: "سیشن کی تصدیق کریں",
    registerBtn: "آئی ڈی بنائیں اور داخل ہوں",
    backupWarning: "اپنا نیکسس آئی ڈی محفوظ جگہ پر لکھیں۔ پاس ورڈ کیساتھ یہ کسی بھی ڈیوائس پر تمام چیٹس اور وال پیپرز کی بحالی کو ممکن بناتا ہے۔",
    backupWarningTitle: "اہم سیکیورٹی معلومات",
    notRegisteredYet: "اکاؤنٹ نہیں ہے؟ نیا نیکسس آئی ڈی بنائیں",
    alreadyRegistered: "پہلے سے رجسٹرڈ ہیں؟ لاگ ان پینل",
    recoverBtn: "کلاؤڈ ڈیٹا بحال کریں",
    chatsTab: "چیٹس",
    callsTab: "کالز",
    statusTab: "اسٹیٹس",
    contactsTab: "رابطے",
    settingsTab: "ترتیبات",
    searchPlaceholder: "رابطے یا آئی ڈی تلاش کریں...",
    noChats: "کوئی گفتگو موجود نہیں ہے! رابطوں میں جا کر گپ شپ شروع کریں۔",
    onlineText: "آن لائن",
    typingText: "ٹائپ کر رہا ہے...",
    offlineText: "آف لائن",
    lastSeenText: "آخری بار دیکھا گیا",
    callIncoming: "صوتی کال آ رہی ہے...",
    callOutgoing: "کال جا رہی ہے...",
    callConnected: "محفوظ رابطہ قائم ہو گیا ہے",
    callConnecting: "کال ملائی جا رہی ہے...",
    callEnded: "کال ختم ہو گئی",
    muteMicrophone: "خاموش",
    speakerMode: "اسپیکر",
    hangupBtn: "بند کریں",
    acceptBtn: "جواب دیں",
    rejectBtn: "کاٹ دیں",
    statusPrivacyLabel: "اسٹیٹس پرائیویسی",
    readReceiptsLabel: "پڑھنے کی تصدیق (نیلے نشانات)",
    blockedUsersLabel: "بلاک شدہ صارفین",
    themeLabel: "تھیم کا انتخاب",
    accentColorLabel: "مرکزی رنگ کا انتخاب",
    bubbleColorLabel: "پیغام کے بلبلے کا رنگ",
    languageLabel: "زبان تبدیل کریں",
    securityLabel: "خفیہ کاری مطابقت",
    archiveCheck: "چیٹ آرکائیو کریں",
    lockCheck: "لاک چیٹ (پن کوڈ مطلوب ہے)",
    pollQuestion: "پول کا سوال",
    pollOptions: "جوابات کے آپشن (کوما سے الگ کریں)",
    pollCreateBtn: "پول بنا کر بھیجیں",
    desktopModeLabel: "ڈیسک ٹاپ موڈ",
    activeNow: "آن لائن صارفین",
    copiedToken: "نیکسس آئی ڈی کاپی ہو گئی!",
    backupSuccess: "کلاؤڈ بیک اپ مکمل طور پر ہم آہنگ کر دیا گیا ہے!",
    restoreSuccess: "پروفائل، گپ شپ اور اسٹیٹس کلاؤڈ سے بحال کر دیے گئے ہیں!",
    aboutSection: "نیکسس میسنجر بغیر کسی موبائل سم کے، عالمی ورچوئل آئی ڈیز پر مکمل محفوظ گفتگو کی رسائی فراہم کرتا ہے۔",
    starredLabel: "پسندیدہ پیغامات",
    saveIdTitle: "مبارک ہو! نیکسس آئی ڈی مل گئی",
    saveIdDesc: "یہ آپ کا مستقل نیکسس ورچوئل آئی ڈی ہے۔ اسے اپنے پاس ورڈ کیساتھ محفوظ کر لیں تاکہ ڈیٹا بحال کیا جا سکے ہمیشہ۔",
    savedBtn: "میں نے لکھ لیا ہے",
    muteCheck: "آواز بند کریں",
    clearCheck: "چیٹ صاف کریں",
    typingIndicatorLabel: "لکھنے کی حالت کا اظہار",
    uploadQualityLabel: "میڈیا اپ لوڈ کی کوالٹی"
  },
  es: {
    splashText: "Seguro. Distribuido. Mensajería con ID Virtual.",
    loginTitle: "Ingresar a Nexus Messenger",
    loginSubtitle: "Acceso instantáneo a su panel de comunicaciones globales",
    registerTitle: "Crear una cuenta",
    registerSubtitle: "Obtenga su ID de Nexus virtual único automáticamente",
    nexusIdLabel: "ID de Nexus (comienza con +0)",
    passwordLabel: "Contraseña",
    nameLabel: "Nombre de perfil",
    bioLabel: "Biografía/Información",
    avatarLabel: "Foto de perfil",
    loginBtn: "Iniciar Sesión",
    registerBtn: "Generar ID e Ingresar",
    backupWarning: "Conserve su ID de Nexus cuidadosamente para posibles restauraciones en la nube de sus chats, estados e historial.",
    backupWarningTitle: "Aviso de identidad virtual de Nexus",
    notRegisteredYet: "¿Nuevo aquí? Regístrese para reclamar su ID virtual",
    alreadyRegistered: "¿Ya está registrado? Ingrese aquí",
    recoverBtn: "Gestionar Restauración Cloud",
    chatsTab: "Chats",
    callsTab: "Llamadas",
    statusTab: "Estados",
    contactsTab: "Contactos",
    settingsTab: "Ajustes",
    searchPlaceholder: "Buscar chats, nombres o ID de Nexus...",
    noChats: "No se encontraron conversaciones. ¡Busque contactos para comenzar!",
    onlineText: "Activo ahora",
    typingText: "escribiendo...",
    offlineText: "Desconectado",
    lastSeenText: "Última vez vista recientemente",
    callIncoming: "Llamada de voz entrante...",
    callOutgoing: "Enlazando llamada segura...",
    callConnected: "Conexión cifrada establecida",
    callConnecting: "Estableciendo enlace de satélite...",
    callEnded: "Llamada finalizada con éxito",
    muteMicrophone: "Silenciar",
    speakerMode: "Altavoz",
    hangupBtn: "Desconectar",
    acceptBtn: "Aceptar Llamada",
    rejectBtn: "Rechazar",
    statusPrivacyLabel: "Privacidad de Estados",
    readReceiptsLabel: "Confirmaciones de lectura (Doble tic visto)",
    blockedUsersLabel: "Contactos bloqueados",
    themeLabel: "Apariencia visual",
    accentColorLabel: "Color de acento del sistema",
    bubbleColorLabel: "Color de mis burbujas",
    languageLabel: "Idioma de la plataforma",
    securityLabel: "Criptografía Sincronizada",
    archiveCheck: "Archivar conversación",
    lockCheck: "Bloquear Chat (con PIN)",
    pollQuestion: "Pregunta de Encuesta",
    pollOptions: "Opciones (separadas por comas)",
    pollCreateBtn: "Lanzar Encuesta Informativa",
    desktopModeLabel: "Modo de Escritorio Expandido",
    activeNow: "Sesiones globales activas",
    copiedToken: "¡Copiado el ID Virtual de Nexus!",
    backupSuccess: "¡Base de datos de recuperación en la nube sincronizada con éxito!",
    restoreSuccess: "¡Chats, biografía, estados y multimedia totalmente restaurados!",
    aboutSection: "Nexus Messenger permite chats seguros de extremo a extremo a través de identificadores digitales virtuales (+0) sin requisitos de red móvil.",
    starredLabel: "Mensajes Destacados",
    saveIdTitle: "¡Identidad de Nexus Concedida!",
    saveIdDesc: "Aquí está su identidad virtual persistente de Nexus para comunicaciones cifradas globales.",
    savedBtn: "Lo he guardado seguro",
    muteCheck: "Silenciar notificaciones",
    clearCheck: "Vaciar conversación",
    typingIndicatorLabel: "Transmitir estado de escritura",
    uploadQualityLabel: "Calidad de carga de medios"
  },
  fr: {
    splashText: "Sécurisé. Distribué. ID Virtuel.",
    loginTitle: "Connexion Nexus Messenger",
    loginSubtitle: "Accédez à votre espace sécurisé global",
    registerTitle: "Rejoindre le réseau",
    registerSubtitle: "Générez votre ID virtuel unique",
    nexusIdLabel: "Identifiant Nexus (commence par +0)",
    passwordLabel: "Mot de passe",
    nameLabel: "Nom d'affichage",
    bioLabel: "Statut/Biographie",
    avatarLabel: "Photo de profil",
    loginBtn: "Connexion",
    registerBtn: "S'inscrire et obtenir l'ID",
    backupWarning: "Conservez précieusement votre ID Nexus. Combiné au mot de passe, il restaure votre profil, vos statuts et vos conversations sur n'importe quel appareil.",
    backupWarningTitle: "Avertissement d'identité virtuelle",
    notRegisteredYet: "Nouveau? Inscrivez-vous pour obtenir votre identifiant",
    alreadyRegistered: "Déjà inscrit? Aller à la page de connexion",
    recoverBtn: "Restauration Cloud",
    chatsTab: "Salons",
    callsTab: "Appels",
    statusTab: "Actualités",
    contactsTab: "Membres",
    settingsTab: "Ajustes",
    searchPlaceholder: "Chercher Nexus ID ou nom...",
    noChats: "Aucune discussion. Allez dans l'onglet Membres pour démarrer un chat!",
    onlineText: "En ligne",
    typingText: "écrit...",
    offlineText: "Hors ligne",
    lastSeenText: "Vu récemment",
    callIncoming: "Appel vocal entrant...",
    callOutgoing: "Appel de satellite sécurisé...",
    callConnected: "Connexion chiffrée établie",
    callConnecting: "Initialisation de la liaison...",
    callEnded: "Appel terminé",
    muteMicrophone: "Couper",
    speakerMode: "Haut-parleur",
    hangupBtn: "Raccrocher",
    acceptBtn: "Décrocher",
    rejectBtn: "Refuser",
    statusPrivacyLabel: "Confidentialité d'actualités",
    readReceiptsLabel: "Accusés de lecture (Doble coche bleu)",
    blockedUsersLabel: "Utilisateurs bloqués",
    themeLabel: "Thème d'affichage",
    accentColorLabel: "Couleur d'accentuation",
    bubbleColorLabel: "Couleur de mes messages",
    languageLabel: "Langue du système",
    securityLabel: "Criptographie quantique",
    archiveCheck: "Archiver la discussion",
    lockCheck: "Verrouiller le salon (PIN requise)",
    pollQuestion: "Sujet du sondage",
    pollOptions: "Options (séparées par des virgules)",
    pollCreateBtn: "Créer le sondage",
    desktopModeLabel: "Forcer l'affichage PC",
    activeNow: "Liaisons mondiales actives",
    copiedToken: "ID virtuel Nexus copié dans le presse-papiers!",
    backupSuccess: "Sauvegarde cloud cryptée synchronisée!",
    restoreSuccess: "Profil, messages, fils de discussion et médias entièrement restaurés!",
    aboutSection: "Nexus Messenger fonctionne en chiffrement de bout en bout complet sur des identifiants virtuels sans utiliser de puce SIM.",
    starredLabel: "Favoris",
    saveIdTitle: "Identité Nexus Émise!",
    saveIdDesc: "Conservez cet identifiant numérique pour l'authentification et les restaurations futures.",
    savedBtn: "Enregistré avec succès",
    muteCheck: "Sourdine",
    clearCheck: "Effacer les messages",
    typingIndicatorLabel: "Indicateur d'écriture",
    uploadQualityLabel: "Profil de bande passante média"
  },
  hi: {
    splashText: "सुरक्षित। विकेंद्रीकृत। वर्चुअल आईडी मैसेजिंग।",
    loginTitle: "नेक्सस मैसेंजर लॉगिन",
    loginSubtitle: "अपने वैश्विक संचार पैनल तक तुरंत पहुंचें",
    registerTitle: "नया वर्चुअल खाता बनाएं",
    registerSubtitle: "ऑटोमेटिक विशिष्ट नेक्सस वर्चुअल आईडी प्राप्त करें",
    nexusIdLabel: "नेक्सस आईडी (+0 से शुरू)",
    passwordLabel: "सुरक्षित पासवर्ड",
    nameLabel: "आपका नाम",
    bioLabel: "बायो / स्टेटस जानकारी",
    avatarLabel: "प्रोफ़ाइल चित्र लिंक",
    loginBtn: "प्रमाणित करें",
    registerBtn: "आईडी बनाएं और प्रवेश करें",
    backupWarning: "अपनी नेक्सस वर्चुअल आईडी संभाल कर रखें। पासवर्ड के साथ यह किसी भी डिवाइस पर आपकी चैट, इतिहास, और सेटिंग्स को बहाल करने देता है।",
    backupWarningTitle: "नेक्सस सुरक्षा सूचना",
    notRegisteredYet: "नए यूज़र हैं? अभी अपनी आईडी जनरेट करें",
    alreadyRegistered: "पहले से खाता है? लॉगिन करें",
    recoverBtn: "क्लाउड डेटा पुनर्स्थापना",
    chatsTab: "चैट्स",
    callsTab: "कॉल",
    statusTab: "स्टेटस",
    contactsTab: "संपर्क",
    settingsTab: "सेटिंग्स",
    searchPlaceholder: "चैट या नेक्सस आईडी खोजें...",
    noChats: "कोई सक्रिय वार्तालाप नहीं है। संपर्क सूची में जाएं और चैट शुरू करें!",
    onlineText: "अभी सक्रिय",
    typingText: "टाइप कर रहे हैं...",
    offlineText: "ऑफ़लाइन",
    lastSeenText: "हाल ही में सक्रिय",
    callIncoming: "आने वाली वॉयस कॉल...",
    callOutgoing: "सुरक्षित वॉयस लिंक कॉल...",
    callConnected: "एन्क्रिप्टेड सुरक्षित कनेक्शन स्थापित",
    callConnecting: "कनेक्शन स्थापित किया जा रहा है...",
    callEnded: "कॉल सफलतापूर्वक समाप्त",
    muteMicrophone: "म्यूट",
    speakerMode: "स्पीकर",
    hangupBtn: "काटें",
    acceptBtn: "कॉल उठाएं",
    rejectBtn: "अस्वीकार करें",
    statusPrivacyLabel: "स्टेटस प्राइवेसी साझाकरण",
    readReceiptsLabel: "पढ़े गए संदेश की टिक (डबल-टिक)",
    blockedUsersLabel: "ब्लॉक की गई आईडी संचिका",
    themeLabel: "विज़ुअल इंटरफेस थीम",
    accentColorLabel: "ऐप का रंग विकल्प",
    bubbleColorLabel: "मेरे संदेशों का रंग",
    languageLabel: "सिस्टम की भाषा",
    securityLabel: "क्वांटम एन्क्रिप्शन",
    archiveCheck: "चैट आर्काइव करें",
    lockCheck: "चैट लॉक करें (पिन कोड आवश्यक)",
    pollQuestion: "पोल का मुख्य विषय",
    pollOptions: "विकल्प (अल्पविराम , से अलग करें)",
    pollCreateBtn: "पोल लॉन्च करें",
    desktopModeLabel: "डेस्कटॉप मोड लेआउट",
    activeNow: "विश्वभर में लाइव यूज़र्स",
    copiedToken: "नेक्सस वर्चुअल आईडी कॉपी हो गई है!",
    backupSuccess: "क्लाउड डेटा बैकअप सफलतापूर्वक सिंक हो गया!",
    restoreSuccess: "प्रोफ़ाइल, चैट सूची, और स्टेटस इतिहास पूरी तरह बहाल!",
    aboutSection: "नेक्सस मैसेंजर बिना सिम कार्ड के वर्चुअल वर्चुअल (+0) आईडी पर सुरक्षित एन्क्रिप्टेड वार्तालाप प्रदान करता है।",
    starredLabel: "पसंदीदा संदेश",
    saveIdTitle: "नेक्सस विज़ुअल आईडी प्रदान की गई!",
    saveIdDesc: "यह आपका स्थायी नेक्सस वर्चुअल आईडी है। इसे लिखकर सुरक्षित रख लें ताकि किसी भी वक्त डेटा रिकवर कर सकें।",
    savedBtn: "मैंने सुरक्षित रख लिया है",
    muteCheck: "सूचनाएं म्यूट करें",
    clearCheck: "चैट खाली करें",
    typingIndicatorLabel: "टाइपिंग स्टेटस ब्रॉडकास्ट",
    uploadQualityLabel: "मीडिया अपलोड की गुणवत्ता"
  },
  tr: {
    splashText: "Güvenli. Dağıtık. Sanal ID Mesajlaşma.",
    loginTitle: "Nexus Messenger Giriş",
    loginSubtitle: "Küresel iletişim panelinize anında erişin",
    registerTitle: "Kayıt Ol",
    registerSubtitle: "Otomatik benzersiz sanal Nexus numaranızı alın",
    nexusIdLabel: "Nexus Kimliği (+0 ile başlar)",
    passwordLabel: "Şifre",
    nameLabel: "Profil Adınız",
    bioLabel: "Hakkımda Durumu",
    avatarLabel: "Profil Fotoğrafı URL veya Base64",
    loginBtn: "Kimliği Doğrula",
    registerBtn: "Nexus ID Oluştur ve Giriş Yap",
    backupWarning: "Nexus ID'nizi ve şifrenizi güvenli saklayın. Bu bilgiler tüm sohbetlerinizi, durumlarınızı ve geçmişinizi buluttan geri yüklemenizi sağlar.",
    backupWarningTitle: "Nexus Kimlik Uyarısı",
    notRegisteredYet: "Yeni misiniz? Sanal Nexus kimliği almak için kaydolun",
    alreadyRegistered: "Kayıtlı mısınız? Buradan giriş yapın",
    recoverBtn: "Bulut Geri Yükleme Yönetimi",
    chatsTab: "Sohbetler",
    callsTab: "Aramalar",
    statusTab: "Durum",
    contactsTab: "Kişiler",
    settingsTab: "Ayarlar",
    searchPlaceholder: "Sohbet, kişi ya da Nexus ID ara...",
    noChats: "Sohbet bulunamadı. Kişilerden veya bir Nexus ID yazarak mesajlaşmaya başlayın!",
    onlineText: "Çevrimiçi",
    typingText: "yazıyor...",
    offlineText: "Çevrimdışı",
    lastSeenText: "Yakınlarda çevrimiçiydi",
    callIncoming: "Gelen sesli arama...",
    callOutgoing: "Güvenli bağlantı kuruluyor...",
    callConnected: "Şifreli bağlantı sağlandı",
    callConnecting: "Güvenli hat aranıyor...",
    callEnded: "Arama sonlandırıldı",
    muteMicrophone: "Sessiz",
    speakerMode: "Hoparlör",
    hangupBtn: "Kapat",
    acceptBtn: "Aramayı Cevapla",
    rejectBtn: "Reddet",
    statusPrivacyLabel: "Durum Gizliliği",
    readReceiptsLabel: "Okundu bilgisi (Çift mavi tik)",
    blockedUsersLabel: "Engellenen Kişiler",
    themeLabel: "Görsel Tema",
    accentColorLabel: "Tema rengi seçimi",
    bubbleColorLabel: "Benim mesaj rengim",
    languageLabel: "Platform dili",
    securityLabel: "Kuantum Kriptografi",
    archiveCheck: "Sohbeti Arşivle",
    lockCheck: "Sohbeti Kilitle (PIN gerektirir)",
    pollQuestion: "Anket Sorusu",
    pollOptions: "Seçenekler (virgülle ayırın)",
    pollCreateBtn: "Anketi Paylaş",
    desktopModeLabel: "Geniş Masaüstü Görünümü",
    activeNow: "Dünya geneli aktif oturumlar",
    copiedToken: "Nexus Sanal Kimliği kopyalandı!",
    backupSuccess: "Şifreli bulut yedeklemesi başarıyla senkronize edildi!",
    restoreSuccess: "Profiliniz, kişileriniz ve geçmiş sohbetleriniz kurtarıldı!",
    aboutSection: "Nexus Messenger, herhangi bir hücresel SIM gereksinimi olmaksızın, tamamen şifreli sanal kimlikler (+0) üzerinden iletişim sağlar.",
    starredLabel: "Yıldızlı Mesajlar",
    saveIdTitle: "Nexus Kimliğiniz Tanımlandı!",
    saveIdDesc: "Bu sanal kimlik kalıcıdır. Şifreniz ile bulut verilerinize erişmek için güvenli bir yere kaydedin.",
    savedBtn: "Güvenli bir yere kaydettim",
    muteCheck: "Bildirimleri sessize al",
    clearCheck: "Sohbet geçmişini sil",
    typingIndicatorLabel: "Yazıyor bilgisini göster",
    uploadQualityLabel: "Medya yükleme kalitesi"
  }
};
